### ISSUE TITLE
extends and scope

### ISSUE THREAD

**Issue by lalop** [leafo/scssphp#117]
Hello,
I've an issue with `@extends` in a scope.
for exemple this scss code :
```scss
body{
  .to-extend{
    color: red;
  }
  .test{
    @extend .to-extend;
  }
}
```
is compiled in :
```css
body .to-extend, body body .test, body body .test {
   color: red; }
```
instead of
```css
body .to-extend, body .test {
  color: red; }
```

I push a test https://github.com/lalop/scssphp/commit/c35c43cebb16e7a22bd2ec81d096449173f79c69
