### ISSUE TITLE
Counter variable is lost inside of @content block

### ISSUE THREAD

**Issue by sergeylukin** [leafo/scssphp#120]
Similar to #90 and #93

``` scss
@mixin respond-to($media) {
  // ..strip $media conditional logic for the sake of simplicity
  @content;
}

@include respond-to(handhelds) {
  @for $i from 1 through 2 {
    .grid-#{$i} { width: 100%; }
  }
}
```

outputs:

```
.grid- {
  width: 100%; }

.grid- {
  width: 100%; }
```

instead of:

```
.grid-1 {
  width: 100%; }

.grid-2 {
  width: 100%; }
```
