### ISSUE TITLE
@while doesn't work in @content block

### ISSUE THREAD

**Issue by sergeylukin** [leafo/scssphp#121]
Similar to #120 with an exception that this code doesn't compile at all (ends up with `Allowed memory size exhausted` fatal error):

``` scss
@mixin respond-to($media) {
  // ..strip $media conditional logic for the sake of simplicity
  @content;
}

@include respond-to(handhelds) {
  $i: 1;
  @while $i <= 2 {
    .grid-#{$i} { width: 100%; }
    $i: $i + 1;
  }
}
```

Expected output is:

```
.grid-1 {
  width: 100%; }

.grid-2 {
  width: 100%; }
```
