### ISSUE TITLE
Bug with variable arguments ?

### ISSUE THREAD

**Issue by stevenart** [leafo/scssphp#124]
Hey,

I found a weird thing with variables arguments : 
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_arguments

The example on the official doc is not working for me : 

``` SCSS
@mixin box-shadow($shadows...) {
  -moz-box-shadow: $shadows;
  -webkit-box-shadow: $shadows;
  box-shadow: $shadows;
}

.shadows {
  @include box-shadow(0px 4px 5px #666, 2px 6px 10px #999);
}
```

Is compiled to : 

``` CSS
.shadows {
  -moz-box-shadow: 0px 4px 5px #666;
  -webkit-box-shadow: 0px 4px 5px #666;
  box-shadow: 0px 4px 5px #666;
}
```

(the second shadow is deleted)

Anyone else habing this problem ?
No PHP error is occuring BTW.
