### ISSUE TITLE
Two issues with comments

### ISSUE THREAD

**Issue by squarestar** [leafo/scssphp#125]
I have a file named `_resources.scss` that is being imported using `@import 'resources';`

The first issue is that, according to the SASS reference, a file whose name starts with an underscore and is imported using just its handle should not be compiled into the CSS output. However block comments are being imported and rendered, but in a quirky way, which is the second issue:

In that resources file, any mixin that is followed by one or more block comments `/* ... */` will have those comments inserted before the closing brace of the `@included` rule.

A concrete example:

In the `resources` file:

``` scss
@mixin BoxShadow ($x: 0, $y: 0, $blur: 1px, $spread: 1px, $color: #000, $inset: false) {
    @if $inset {
        $shadow: $x $y $blur $spread $color inset;
    } @else {
        $shadow: $x $y $blur $spread $color;
    }
    -moz-box-shadow:    $shadow;
    -webkit-box-shadow: $shadow;
     box-shadow:        $shadow;
}
/* COLOURS, GRADIENTS, SHADOWS */
/* A collection of mixins */
```

In the calling file:

``` scss
div#main {
  @include BoxShadow(0, 0, 5px, 0, #ddd, inset);
}
```

The resulting css:

``` css
div#main {
  box-shadow: 0 0 5px 0 #ddd inset;
  /* COLOURS, GRADIENTS, SHADOWS */
  /* A collection of mixins */ }
```

This will happen for every call of `@include BoxShadow`
