### ISSUE TITLE
Nesting not working with interpolated strings

### ISSUE THREAD

**Issue by kasperisager** [leafo/scssphp#127]
Consider the following bit of Sass:

```scss
.element {
  #{".one, .two"} {
    property: value;
  }
}
```

This is supposed to compile to:

```scss
.element .one, .element .two {
  property: value;
}
```

But instead compiles to the following using scssphp:

```scss
.element .one, .two {
  property: value;
}
```

Any idea what might be wrong?
