### ISSUE TITLE
@charset not working properly

### ISSUE THREAD

**Issue by Korikulum** [leafo/scssphp#136]
The `@charset` rule is not being compiled properly. According to [the docs](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#encodings) only the first `@charset` should be used. It should also be placed at the top of the stylesheet.

scss:
```scss
.class1 {
  padding: 10px;
  color: green;
  border: {
    left-color: red;
    right-color: blue;
  }
}

@import url(http://fonts.googleapis.com/css?family=Alegreya+Sans);

@charset "utf-8";

.class2 {
  @extend .class1;
  border-color: green;
}

.class3 {
  @extend .class1;
  border-color: red;
}

@charset 'iso-8859-15';

.class4 {
  @extend .class1;
  border-color: yellow;
}
```
Expected result:
```css
@charset "utf-8";
@import url(http://fonts.googleapis.com/css?family=Alegreya+Sans);

.class1, .class2, .class3, .class4 {
  padding: 10px;
  color: green;
  border-left-color: red;
  border-right-color: blue; }

.class2 {
  border-color: green; }

.class3 {
  border-color: red; }

.class4 {
  border-color: yellow; }
```
Actual result:
```css
@import url(http://fonts.googleapis.com/css?family=Alegreya+Sans);
@charset "utf-8";
@charset 'iso-8859-15';

.class1, .class2, .class3, .class4 {
  padding: 10px;
  color: green;
  border-left-color: red;
  border-right-color: blue; }

.class2 {
  border-color: green; }

.class3 {
  border-color: red; }

.class4 {
  border-color: yellow; }
```
