### ISSUE TITLE
Nested extend error

### ISSUE THREAD

**Issue by ntomka** [leafo/scssphp#158]
Input:

```SCSS
.navbar {
  .navbar-brand {
    font-weight: bold;
    text-shadow: none;
    color: #fff;

    &:hover {
      @extend .navbar-brand;
    }
  }
}
```

Desired output:
```SCSS
.navbar .navbar-brand, .navbar .navbar-brand:hover {
  font-weight: bold;
  text-shadow: none;
  color: #fff;
}
```

But I get "Maximum function nesting level of '100' reached, aborting!" error. Any idea? Am I doing wrong something?

This snippet works here: http://sassmeister.com/ even when I set it to use 3.2.17 compiler.
