### ISSUE TITLE
Nesting issue with list

### ISSUE THREAD

**Issue by squarestar** [leafo/scssphp#160]
The code below doesn't work as expected. It should produce:
```css
#secondary h1, #secondary h2, #secondary h3, #secondary h4, #secondary h5, #secondary h6 {
  color: #e6e6e6;
}
```
But actually produces:
```css
#secondary h1, h2, h3, h4, h5, h6 {
  color: #e6e6e6;
}
```
The SCSS:
```scss
@function H($el:false)
{
  $h: ();
	$newList: ();
	@each $ord in 1,2,3,4,5,6 {
		@if $el {
			$h: h#{$ord $el};
		} @else {
			$h: h#{$ord};
		}
		$newList: append($newList, $h, comma);
	}
	@return $newList;
}

@mixin H($prop, $val, $el:false) {
	$list: H($el);
	#{$list} {
		#{$prop}: $val;
	}
}

#secondary {
	@include H(color,  #e6e6e6);
}
```
I checked that it works as expected in sassmeister using SCSS v3.2
