### ISSUE TITLE
it don't compile the code of my imported files

### ISSUE THREAD

**Issue by ajabep** [leafo/scssphp#183]
Hello,

I've try to import some files. But sassphp have import only mixins and variables, but not the code of my imported files. :(

My `index.scss` file :

``` scss
@import "general";

.tagList,
.description {
    @include text-overflow( ellipsis );
    @include transition($transition);
    overflow:hidden;
}
```

my `_general.scss` file :

``` scss
@import "variables";
@import "mixins";



*,
*::before,
*::after {
    -webkit-box-sizing: border-box; /* Safari/Chrome, other WebKit */
       -moz-box-sizing: border-box; /* Firefox, other Gecko */
            box-sizing: border-box;
}

/* and others */
```

my `_variables.scss` file :

``` scss
$transition : .5s;
$backgroundObjects: #fff;
$heightObject: 140px;

/* and others */
```

my `_mixins.scss` file :

``` scss
@mixin transition($transition) {
    -webkit-transition: $transition;
       -moz-transition: $transition;
         -o-transition: $transition;
            transition: $transition;
}

/* and others */
```

and the output :

``` css
.tagList,
.description {
  -o-text-overflow: ellipsis;
  text-overflow: ellipsis;
  -webkit-transition: 0.5s;
  -moz-transition: 0.5s;
  -o-transition: 0.5s;
  transition: 0.5s;
  overflow:hidden;
}
```
