### ISSUE TITLE
Issue with :selectors

### ISSUE THREAD

**Issue by rossxwest** [leafo/scssphp#199]
It seems the extending of selectors that have a :selector on them is broken. It will create additional selectors during compile. See the example below:

Input:
``` css
.abc {
  color: #ddd;
}

a.abc:hover {
  text-decoration: underline; 
}

small {
  @extend .abc;
  font-weight: italic;
}
```

Output:
``` css
/* compiled by scssphp v0.1.0 on Tue, 12 Aug 2014 13:39:06 -0700 (0.0011s) */

.abc, small {
  color: #ddd; }

a.abc:hover, a:hover {
  text-decoration: underline; }

small {
  font-weight: italic; }
```

Expected Output:
``` css
.abc, small {
  color: #ddd; }

a.abc:hover {
  text-decoration: underline; }

small {
  font-weight: italic; }
```
