### ISSUE TITLE
Self (&) Selector is broken

### ISSUE THREAD

**Issue by leafo** [leafo/scssphp#21]
``` scss
.main {
    .message {
        .nice-fonts & {
            font-size: 24px;
        }
    }
}
```

Compiles to:

``` css
.main .nice-fonts .message {
  font-size: 24px; }
```

Expect:

``` css
.nice-fonts .main .message {
  font-size: 24px; }
```
