### ISSUE TITLE
Wrong media queries

### ISSUE THREAD

**Issue by hason** [leafo/scssphp#24]
Expected result for

``` scss
@mixin color {
    color: red;
    .success {
         color: green;
    }
}

div {
    position: absolute;
    $y: 2em;
    @media screen {
        top: 0;
        $x: 5px;
        p {
            margin: $x;
        }
        bottom: 6em + $y;
        @include color;
    }
}
```

is

``` css
div {
  position: absolute; }
  @media screen {
    div {
      top: 0;
      bottom: 8em;
      color: red; }
      div p {
        margin: 5px; }
      div .success {
        color: green; } }
```

Current wrong result is

``` css
div {
  position: absolute; }
  @media screen {
    top: 0;
    bottom: 8em;
    color: red;
  div p {
    margin: 5px; }
  div .success {
    color: green; } }
```
