### ISSUE TITLE
Foundation Text Input Issue

### ISSUE THREAD

**Issue by vita10gy** [leafo/scssphp#248]
In foundation this code exists:

```scss
    #{text-inputs(all, 'input')} {
      -webkit-appearance: none;
      -moz-appearance: none;
      border-radius: 0;
      @include form-element;
      @if $input-include-glowing-effect == false {
        -webkit-transition: border-color $input-transition-fade-time $input-transition-fade-timing-function, background $input-transition-fade-time $input-transition-fade-timing-function;
        -moz-transition: border-color $input-transition-fade-time $input-transition-fade-timing-function, background $input-transition-fade-time $input-transition-fade-timing-function;
        -ms-transition: border-color $input-transition-fade-time $input-transition-fade-timing-function, background $input-transition-fade-time $input-transition-fade-timing-function;
        -o-transition: border-color $input-transition-fade-time $input-transition-fade-timing-function, background $input-transition-fade-time $input-transition-fade-timing-function;
        transition: border-color $input-transition-fade-time $input-transition-fade-timing-function, background $input-transition-fade-time $input-transition-fade-timing-function;
      }
      &.radius {
        @include radius($input-border-radius);
      }
    }
```

The problem is that .radius only gets applied to the last thing text-input() returns, thus the "@include radius(" styles get applied to everything except whatever happens to be last.

It also applies the .disabled coloring to everything, which comes from the form-element line.
