### ISSUE TITLE
@extend working unexpected

### ISSUE THREAD

**Issue by Jackysi** [leafo/scssphp#28]
```scss
#content {

		.social-login {
			display: block;
			float: right;
			margin-right: 15px;
			width: 250px;
			
				.facebook {
					display: block;
					width: 255px;
					height: 42px;
					background: transparent url('images/login-btns.png') no-repeat;
					background-position: 0 0;
				
					&:hover {
						background-position: 0 -43px;
						}
				
					&:focus, &:active {
						background-position: 0 -86px;
						}
				}
				
				.twitter {
				
					@extend .facebook;
					background-position: 0 -129px;
					
					&:hover {
						background-position: 0 -172px;
					}
					
					&:active, &:focus {
						background-position: 0 -215px;
					}
				}
					
		}
}
```

Compiles to:

```css
#content .social-login .facebook,#content .social-login .social-login .twitter,#content .social-login .social-login .twitter {
display:block;
width:255px;
height:42px;
background:transparent url(images/login-btns.png) no-repeat;
background-position:0 0;
}
```

Expected :

```css
#content .social-login .facebook, #content .social-login .twitter, #content .social-login .google {
  display: block;
  width: 255px;
  height: 42px;
  background: transparent url("images/login-btns.png") no-repeat;
  background-position: 0 0;
}
```

I'm not sure I've taken the correct path to do this though, but this is defo bug cause in Ruby it compiles as above.

^^
