### ISSUE TITLE
scss with &:not()::before not compiling correctly

### ISSUE THREAD

**Issue by Zxurian** [leafo/scssphp#286]
https://gist.github.com/Zxurian/54f7cade973e975e5f43

Works on sassmeister, however when actually used, the entire block of

```scss
&:not([class^="icon-"], [class*=" icon-"])::before {
				content: 'ASDF';
			}
```

is omitted from the resulting css.
