### ISSUE TITLE
@extend ing the same thing multiple times is broken

### ISSUE THREAD

**Issue by leafo** [leafo/scssphp#29]
Input: 

``` scss
#something {
    color: red;
}

.x {
    @extend #something;
}

.y {
    @extend #something;
}
```

Expect:

``` css
#something, .x, .y {
  color: red; }
```

Actual:

``` css
#something, .x {
  color: red; }
```
