### ISSUE TITLE
@import statement not working properly?

### ISSUE THREAD

**Issue by martin-pettersson** [leafo/scssphp#294]
The simple setup looks like this:
/scss
|-- style.scss
|-- _variables.scss

Content of the files looks like:
```scss
// style.scss
@import 'variables';

* {
    color: $color;
    background-color: $background_color;
}
```
```scss
// _variables.scss
$color: #444;
$background_color: #efefef;
```
`node-sass --include-path ./ style.scss style.css` produce the correct output:
```css
/* style.css */
* {
  color: #444;
  background-color: #efefef; }
```

But `pscss -i ./ < style.scss > style.css` produces two empty lines:
```css
/* style.css */


```
