### ISSUE TITLE
Swallowed comma before interpolation

### ISSUE THREAD

**Issue by Boddlnagg** [leafo/scssphp#316]
Input: 
```sass
foo, #{x, y} {
    color: #abc;
}
```

Expected output:
```css
foo, x, y {
    color: #abc;
}
```

Actual output:
```css
foox, y {
    color: #abc;
}
```

I'm going to investigate whether I can fix this issue on my own!

[Edit: Further reduced test case.]
