### ISSUE TITLE
@extend with :before causes exception

### ISSUE THREAD

**Issue by Zxurian** [leafo/scssphp#322]
input
```scss
.icon-spinner3:before {
	content: "\eb21";
}

.icon-ajax {
  @extend .icon-spinner3;
}
```

expected output
```css
.icon-spinner3:before, .icon-ajax:before {
  content: "\eb21";
}
```

actual output
```
Warning: preg_match() expects parameter 2 to be string, array given in /var/www/dev.hub/vendor/leafo/scssphp/src/Compiler.php on line 390
19	0.1065	3438080	Leafo\ScssPhp\Compiler->compile( )	.../ScssphpFilter.php:104
20	0.1074	3493656	Leafo\ScssPhp\Compiler->compileRoot( )	.../Compiler.php:166
21	0.1942	4415312	Leafo\ScssPhp\Compiler->flattenSelectors( )	.../Compiler.php:250
22	0.1967	4370920	Leafo\ScssPhp\Compiler->flattenSelectors( )	.../Compiler.php:306
23	0.1968	4371320	Leafo\ScssPhp\Compiler->flattenSelectors( )	.../Compiler.php:306
24	0.1968	4371624	Leafo\ScssPhp\Compiler->matchExtends( )	.../Compiler.php:273
25	0.1968	4372120	Leafo\ScssPhp\Compiler->matchExtendsSingle( )	.../Compiler.php:325
26	0.1968	4372792	preg_match ( )	.../Compiler.php:390
```

for reference the dumped $rawSingle from `matchExtendsSingle` function
```
array (size=1)
  0 => 
    array (size=3)
      0 => string 'number' (length=6)
      1 => string '0' (length=1)
      2 => string '%' (length=1)
```
