### ISSUE TITLE
using @keyframes causes exception when using @extend

### ISSUE THREAD

**Issue by Zxurian** [leafo/scssphp#323]
using the following declaration
```css
@keyframes anim-rotate {
	0% {
		transform: rotate(0);
	}
	
	100% {
		transform: rotate(360deg);
	}
}
```

causes an exception when trying to use `@extend` afterwards (the exception is detailed in #322)
