### ISSUE TITLE
'null' not getting interpolated as empty string

### ISSUE THREAD

**Issue by squarestar** [leafo/scssphp#33]
In this mixin:

``` scss
@mixin Rounded($radius1, $direction: null, $radius2: false) {
    $corner: null;
    @if $direction == TL { $corner: top-left-; }
    @if $direction == TR { $corner: top-right-; }
    @if $direction == BL { $corner: bottom-left-; }
    @if $direction == BR { $corner: bottom-right-; }
    @if $radius2 {
        -webkit-border-#{$corner}radius: $radius1 $radius2;
                border-#{$corner}radius: $radius1 $radius2;
    } @else {
        -webkit-border-#{$corner}radius: $radius1;
                border-#{$corner}radius: $radius1;
    }
}
```

The value of `$corner` is written as 'null' instead of an empty string, as indicated by the manual:

> Null values are treated as empty strings for string interpolation:
> $value: null;
> p:before {
>  content: "I ate #{$value} pies!";
> }
