### ISSUE TITLE
Wrong behaviour of @extend in combination with interpolation of a variable

### ISSUE THREAD

**Issue by theinrichs** [leafo/scssphp#336]
When you put multiple selectors in a variable, you can't use that variable with @extend.

Testing code:
```scss
.selector1 {
    color: blue;
}

.selector2 {
    background: #ccc;
}

/*
multiple selectors in $var
e.G. a lot of Bootstrap components need at least to classes
*/

$var: ".selector1, .selector2";

.master-class {
    // interpolation of the variable is needed since we have a selector in $var
    @extend #{$var};
}
```
Should compile to this:
```css
.selector1, .master-class {
  color: blue;
}

.selector2, .master-class {
  background: #ccc;
}
```
But compiles to that (only selector1 was used by @extend):
```css
.selector1, .master-class {
  color: blue;
}

/* .master-class is missing :( */
.selector2 {
  background: #ccc;
}
```
I don't understand exactly how @extends works in scssphp, but it seems that the interpolation of the variable is done to late.
The statement that'll be appended to the block looks like this without interpolation 

```scss 
@extend .selector1, .selector2;
````
```
Array
(
    [0] => Array
        (
            [0] => Array
                (
                    [0] => .
                    [1] => selector1
                )

        )

    [1] => Array
        (
            [0] => Array
                (
                    [0] => .
                    [1] => selector2
                )

        )

)
```
And like that with interpolation 

```scss 
@extend #{var};
```
```
Array
(
    [0] => Array
        (
            [0] => Array
                (
                    [0] => Array
                        (
                            [0] => interpolate
                            [1] => Array
                                (
                                    [0] => var
                                    [1] => var
                                )

                            [2] =>  
                            [3] => 
                        )

                )

        )
)
```

So we're already on the wrong level of the array when the interpolation kicks in, because the parser recognizes ``` #{$var} ``` as a single selector. Am I right?

Hope that helps!
