### ISSUE TITLE
Variable arguments not working

### ISSUE THREAD

**Issue by squarestar** [leafo/scssphp#34]
According to the documentation, the syntax 

``` scss
element {
 @mixin mixin($args...) {
  property: $args;
 }
}
```

Should compile to:

``` css
element {
 property: arg1 arg2 arg3;
}
```

However, no css appears in the output at all, but the source scss does.
