### ISSUE TITLE
materializecss

### ISSUE THREAD

**Issue by treio** [leafo/scssphp#343]
Hi there,

I'm trying to compile Materialize CSS Framework (http://materializecss.com/) with scssphp and unfortunately I always get following errors:
```
Line 39 WARN: "Unknown `name` in $colors." 

Fatal error: Uncaught exception 'Exception' with message 'expecting color: failed at `$primary-color-light: lighten($primary-color, 15%) !default;` scss/components/_variables.scss on line 3' in /path_to_project/scssphp/src/Parser.php:2161

Stack trace: 
#0 /path_to_project/scssphp/src/Compiler.php(2905): Leafo\ScssPhp\Parser->throwParseError('expecting color', 81) 
#1 /path_to_project/scssphp/src/Compiler.php(3417): Leafo\ScssPhp\Compiler->throwError('expecting color') 
#2 /path_to_project/scssphp/src/Compiler.php(3902): Leafo\ScssPhp\Compiler->assertColor(Array) 
#3 [internal function]: Leafo\ScssPhp\Compiler->libLighten(Array, Object(scssc)) 
#4 /path_to_project/scssphp/src/Compiler.php(2981): call_user_func(Array, Array, Object(scssc)) 
#5 /path_to_project/scssphp/src/Compiler.php(1698): Leafo\ScssPhp\Compiler->callBuiltin('lighten', Array, NULL) 
#6 /path_to_project/scssphp/src/Compiler.php(1168): Leaf in /path_to_project/scssphp/src/Parser.php on line 2161
```
Original code is not touched and standard SASS compilers do the work correctly and this is the reason why I'm posting it here.

I don't think that the problem is in `scss/components/_variables.scss` file, but it looks like the root of problem is coming somewhere from this function (from `scss/components/_color.scss`):
```
@function color($color, $type) {
	@if map-has-key($colors, $color) {
		$curr_color: map-get($colors, $color);
		@if map-has-key($curr_color, $type) {
			@return map-get($curr_color, $type);
		}
	}
	@warn "Unknown `#{name}` in $colors.";
	@return null;
}
```
However, it looks good to me and as other compilers do their work, it's strange.

Any idea how to solve it or where is the problem?
Does anyone tried to compile this Framework using scssphp?

**Comment by treio** [comment]
In addition, the latest release of scssphp is used where the map functions should be already implemented.

**Comment by marcorivm** [comment]
Related error here:
```
ErrorException in Parser.php line 2142:
expecting color: failed at `$primary-color-light: lighten($primary-color, 15%) !default;
`materialize/sass/components/_variables.scss on line 3 
```

**Comment by treio** [comment]
I don't think so. I have spent some time to getting to the rood of error and here is what I have found. 
The problem is with map functions as these functions are not able to accept string based keys.

Example of working SCSS:
```
$set1: (
	color1: blue,
	color2: red
);

$set2: (
	color1: yellow,
	color2: green
);

$colorsets: (
  set1: $set1,
  set2: $set2
);

@function test($set, $color) {
	@if map-has-key($colorsets, $set) {
		$curr_set: map-get($colorsets, $set);
		@if map-has-key($curr_set, $color) {
			@return map-get($curr_set, $color);
		}
		@warn "Unknown `#{$color}` in $curr_set.";
		@return null;
	}
	@warn "Unknown `#{$set}` in $colorsets.";
	@return null;
}

$test-color: test("set1", "color1");
div {color: $test-color}
```

And here is example of SCSS running to fatal error:
```
$set1: (
	"color1": blue,
	"color2": red
);

$set2: (
	"color1": yellow,
	"color2": green
);

$colorsets: (
  "set1": $set1,
  "set2": $set2
);

@function test($set, $color) {
	@if map-has-key($colorsets, $set) {
		$curr_set: map-get($colorsets, $set);
		@if map-has-key($curr_set, $color) {
			@return map-get($curr_set, $color);
		}
		@warn "Unknown `#{$color}` in $curr_set.";
		@return null;
	}
	@warn "Unknown `#{$set}` in $colorsets.";
	@return null;
}

$test-color: test("set1", "color1");
div {color: $test-color}
```
Different is only in `"` on map keys.

**Comment by treio** [comment]
Thank you for fixing this so quickly, it works almost fine.

Unfortunately, there is required one more touch to make this issue fixed - compiled files should not contain quotation marks.

Here is example of what we get with string based keys:
```css
."materialize-red"."lighten-5" {
  background-color: #fdeaeb !important;
}
."materialize-red"-text.text-"lighten-5" {
  color: #fdeaeb !important;
}
."materialize-red"."lighten-4" {
  background-color: #f8c1c3 !important;
}
."materialize-red"-text.text-"lighten-4" {
  color: #f8c1c3 !important;
}
```

And here is example of what we should get:
```css
.materialize-red.lighten-5 {
  background-color: #fdeaeb !important;
}
.materialize-red-text.text-lighten-5 {
  color: #fdeaeb !important;
}
.materialize-red.lighten-4 {
  background-color: #f8c1c3 !important;
}
.materialize-red-text.text-lighten-4 {
  color: #f8c1c3 !important;
}
```

Compiler includes also quotation marks while constructing the final CSS, which is wrong of course.

Btw, great work so far! ;-)
