### ISSUE TITLE
@at-root Variables not defined

### ISSUE THREAD

**Issue by designerno1** [leafo/scssphp#354]
tried to compile this got parser error

Parse error: Undefined variable $padding: failed at `padding: $padding;` /...../ on line 8

```scss
$table-padding: 10px !default;
//$padding: $table-padding;

@mixin table($padding: $table-padding) {
  @at-root {
    tbody {
      padding: $padding;
    }
  }
}
.test{
  .test2{
    padding: 0px;
    @include table;
  }
}
```
