### ISSUE TITLE
index($list,$value) Problem with one in $list

### ISSUE THREAD

**Issue by designerno1** [leafo/scssphp#362]
Hello first of all great work on the new release

found a Problem with index($list,$value)
```scss
.test {
  display: index(nest, nest);
}
```
in a sass compiler it returns 1 in scssphp it returns nothing

http://sass-lang.com/documentation/Sass/Script/Functions.html#index-instance_method
