### ISSUE TITLE
scale-color difference in colors

### ISSUE THREAD

**Issue by designerno1** [leafo/scssphp#363]
i tried this one
```scss
.test {
  color: scale-color(#777, $lightness: -50%);
}
```
in sass compiler it is
```scss
.test {
  color: #3b3b3b;
}
```
in scssphp
```scss
.test {
  color: #3c3c3c;
}
```
it's only small differences but maybe add a testcase for all scale-color opportunities?
