### ISSUE TITLE
CSS hack in mixin eats selector "@media screen and (min-width:0\0) {"

### ISSUE THREAD

**Issue by designerno1** [leafo/scssphp#364]
```scss
@mixin test-mixin($color: #000) {
  @media screen and (min-width:0\0) {
    color: $color;
  }
}
.test{
  @include test-mixin();
}
```
in sass compiler it results in
```css
@media screen and (min-width: 0 \0) {
  .test {
    color: #000; } }
```
in scssphp
```css
@media screen and (min-width:0\0) {
  color: #000;
}
```
setting a correct breakpoint like
```css
@media screen and (min-width:64rem) {
```
it works great but i have to use the css hack
