### ISSUE TITLE
mixin Variable get scoped away from function variable

### ISSUE THREAD

**Issue by designerno1** [leafo/scssphp#365]
worked out this test case
```scss
@function test-function() {
  $str: 'test-function';
  @return $str;
}

@mixin test-mixin {
  $str: 'test-mixin';
  display: $str;
  $new-bp: test-function();
  display: $str;
}

$str: 'global';
.test{
  display: $str;
  @include test-mixin;
  display: $str;
}
```
scss compiler output
```css
.test {
  display: "global";
  display: "test-mixin";
  display: "test-mixin";
  display: "global";
}
```
scssphp output
```css
.test {
  display: 'global';
  display: 'test-mixin';
  display: 'test-function';
  display: 'global';
}
```
seems the $str from the function overrides the $str from the mixin
