### ISSUE TITLE
str-slice negative eliminates to much chars

### ISSUE THREAD

**Issue by designerno1** [leafo/scssphp#366]
testcase
```scss
$str: str-slice("testcase", 1, -2);
.test{
  content: $str;
}
```
output sass compiler
```css
.test {
  content: "testcas";
}
```
output scssphp
```css
.test {
  content: "testca";
}
```
maybe something to do with "end-at Defaults to -1"
http://sass-lang.com/documentation/Sass/Script/Functions.html#str_slice-instance_method
