### ISSUE TITLE
self: in selector

### ISSUE THREAD

**Issue by designerno1** [leafo/scssphp#368]
TestCase

``` scss
.test {
    &:last-child:not(+ &:first-child) {
      padding-left: 10px;
    }
}
```

output sass compiler

``` css
.test:last-child:not( + :first-child) {
  padding-left: 10px;
}
```

output scssphp

``` css
.test self:last-child:not(+ &:first-child) {
  padding-left: 10px;
}
```

it's also inside a mixing the same

**Comment by robocoder** [comment]
Shouldn't the correct output be:
```
.test:last-child:not( + .test:first-child) {
  padding-left: 10px;
}
```
?

**Comment by designerno1** [comment]
SassMeister.com output is
```css
.test:last-child:not(+ :first-child) {
  padding-left: 10px;
}
```
both LibSass 3.2.5 and Ruby 3.4.14
