### ISSUE TITLE
Gradient via compass background-image failes

### ISSUE THREAD

**Issue by jrmyio** [leafo/scssphp#37]
When i do the following:

``` scss
@include background-image(linear-gradient(#1e5266, #1c7f92));
```

The generated output is:

``` css
  background-image: -owg(linear-gradient(#1e5266, #1c7f92));
  background-image: -webkit(linear-gradient(#1e5266, #1c7f92));
  background-image: -moz(linear-gradient(#1e5266, #1c7f92));
  background-image: -o(linear-gradient(#1e5266, #1c7f92));
  background-image: linear-gradient(#1e5266, #1c7f92);
```

This does not work in chrome. The outcome should be:

``` css
  background-image: -owg-linear-gradient(#1e5266, #1c7f92);
  background-image: -webkit-linear-gradient(#1e5266, #1c7f92);
  background-image: -moz-linear-gradient(#1e5266, #1c7f92);
  background-image: -o-linear-gradient(#1e5266, #1c7f92);
  background-image: linear-gradient(#1e5266, #1c7f92);
```

This is the mixin in compass:

``` scss
// Background image property support for vendor prefixing within values.
@mixin background-image(
  $image-1,
  $image-2: false,
  $image-3: false,
  $image-4: false,
  $image-5: false,
  $image-6: false,
  $image-7: false,
  $image-8: false,
  $image-9: false,
  $image-10: false
) {
  $images: compact($image-1, $image-2, $image-3, $image-4, $image-5, $image-6, $image-7, $image-8, $image-9, $image-10);
  $add-pie-bg: prefixed(-pie,   $images) or -compass-list-size($images) > 1;

  @if $experimental-support-for-svg          and prefixed(-svg,    $images) { background-image:    -svg($images); background-size: 100%; }
  @if $support-for-original-webkit-gradients and prefixed(-owg,    $images) { background-image:    -owg($images); }
  @if $experimental-support-for-webkit       and prefixed(-webkit, $images) { background-image: -webkit($images); }
  @if $experimental-support-for-mozilla      and prefixed(-moz,    $images) { background-image:    -moz($images); }
  @if $experimental-support-for-opera        and prefixed(-o,      $images) { background-image:      -o($images); }
  @if $experimental-support-for-pie          and $add-pie-bg                { @warn "PIE does not support background-image. Use @include background(#{$images}) instead." }
                                                                              background-image:         $images ;
}
```
