### ISSUE TITLE
Nested Selector Issue Ruby/LibSass difference

### ISSUE THREAD

**Issue by designerno1** [leafo/scssphp#371]
TestCase

``` scss
ul, ol {
    & & {
      display: block;
    }
  }
```

output sass compiler Ruby

``` css
ul ul, ol ul, ul ol, ol ol {
  display: block;
}
```

output sass compiler LibSass

``` css
ul ul, ol ol {
  display: block;
}
```

output scssphp

``` css
ul ul, ol ol {
  display: block;
}
```
