### ISSUE TITLE
Script eats RAM and dies

### ISSUE THREAD

**Issue by Lewiscowles1986** [leafo/scssphp#384]
The following CSS kills it :cry: 
```scss
$minCols: 2;
$maxCols: 12;

$medium: 50em;
$fullWidth: 70em;

$txtColor: #111111;
$txtColorLight: #ccc;
$highlightActive: #00B1E7;

* {
  box-sizing: border-box;
}
body {
  margin: 0;
  padding: 0;
  color: $txtColor;
  min-width: 320px
  min-height: 320px;
}

img {
  max-width: 100%;
  height: auto;
}
main {
  min-height: 320px;
  min-height: 50vh;
}
nav.nav-menu {
  text-align: center;
  & ul {
    list-style: none;
    margin: 0;
    padding: 0 !important;
    
    & li {
      display: block;
      font-size: 1.25rem;

      & a {
        display: block;
        padding: 1rem;
        text-decoration:none;
        color: #101010;
        border-bottom: 3px solid transparent;
        &:hover, &:target, &:active {
          cursor: pointer;
          border-bottom-color: darken(desaturate($highlightActive,30%),10%);
        }
      }
      &.current-menu-item {
        & a {
          border-bottom-color: darken($highlightActive,5%);
        }
      }
    }
  }
}
.col {
  width: 100%;
}
.tL {
  text-align: left;
}
.tR {
  text-align: right;
}
.tC {
  text-align: center;
}
.tJ {
  text-align: justify;
}

/*
* Project specific CSS (branding.css)
*/
.grid > .row > .col {
  .btn, button {
    border-radius: 0;
    text-align: right;
    font-weight: 700;
  }
  form {
    input, button, textarea {
      display: block;
      width: 100%;
      padding: .25em .5em;
      margin-bottom: 1.5em;
    }
    textarea {
      resize: vertical;
      min-height: 5em;
    }
  }
}
@mixin clearfix() {
  &:before, &:after {
    content: "";
    display: block;
    height: 0;
    width: 100%;
    clear: both;
    display: table;
    zoom: 1;
  }
}

.grid {
  & > .row {
    @include clearfix();
  }
}
@mixin wrap() {
  padding: 1rem 2rem;
}
.wrap {
  @include wrap();
}
@media( max-width: 69.9999rem ) {
  .client-login {
    display: none;
  }
  nav.nav-menu {
    ul {
      li {
        background-color: #005F8A;
        a {
          color: #fefefe;
          &:hover {
            border-bottom-style: solid;
            border-bottom-color: transparent;
          }
        }
        &:hover, &:target, &:active, &.current-menu-item {
          background-color: darken(desaturate($highlightActive,30%),10%);
          color: #fefefe;
        }
        &.current-menu-item {
          background-color: $highlightActive;
          color: #fefefe;
        }
      }
    }
  }
}
@media( min-width: 70rem ) {
  .wrap-lrg {
    @include wrap();
  }
  .grid {
    @for $c from $minCols through $maxCols {
      $myWidth: 100% / $c;
      &.cnt#{$c} {
        & .row {
          position: relative;
          @include clearfix();
          &.wrap {
            @include wrap();
          }
          & > .col {
            width: $myWidth;
            display: block;
            float: left;
            padding: 0;
            margin: 0;
            $colLimit: min($c,$maxCols);
            @for $i from $minCols through $colLimit {
              &.sp#{$i} {
                width: $myWidth * $i;
                &.pull-right {
                  float: right;
                }
              }
            }
            &.pull-right {
              float: right;
            }
          }
        }
      }
    }
  }
  .shadow-top {
    box-shadow: inset 0 .25em .4em -.25em rgba(0,0,0,0.7);
  }
  .shadow-bot {
      box-shadow: inset 0 -.25em .4em -.25em rgba(0,0,0,0.7);
  }
  .shadow-left {
      box-shadow: inset .25em 0 .4em -.25em rgba(0,0,0,0.7);
  }
  .shadow-right {
      box-shadow: inset -.25em 0 .4em -.25em rgba(0,0,0,0.7);
  }

  .wrap, .wrap-lrg {
    max-width: $fullWidth;
    display: block;
    margin: 0 auto;
    position: relative;
  }

  .header {
    min-height: 100px;
    background-color: #fefefe;
    padding: .5rem;
    border-bottom: 1px solid rgba(0,0,0,.6);
    & .row > .col.logo {
      text-align: center;
      padding-top: 1em;
    }
    & .row > h1.col.logo {
      font-weight: 700;
      font-size: 2.5rem;
      padding: 2rem;
    }
    & .client-login {
      text-align: right;
      padding-right: 1rem;
    }
    & nav.horizontal.nav-menu {
      text-align: right;
    }
  }
  main {
    min-height: 70vh;
    header {
      display: block;
      position: relative;
      min-height: 320px;
      padding: 0;
      margin: 0;
      overflow: hidden;
      margin-bottom: 2rem;
      &:before, &:after {
        content: "";
        left: 0;
        display: block;
        position: absolute;
        z-index: 1;
        width: 100%;
        height: 20px;
      }
      &:before {
        @extend .shadow-top;
        top: 0;
      }
      &:after {
        @extend .shadow-bot;
        top: auto;
        bottom: .2em;
      }
      & > img.featured.main {
        margin: 0;
        display: block;
      }
    }
  }
  nav.horizontal.nav-menu {
    padding: .5rem 0;
    & ul {
      margin: 0;
      padding: 0;
      width: 100%;
      display: block;
      list-style: none;
      & li {
        padding: 0rem;
        display: inline-block;
        &:nth-child(-n+5):after {
          content: "|";
          color: $txtColor;
          padding-left: .5rem;
        }
        &:last-child {
          padding-right: 1rem;
        }
      }
      & a {
        padding: .25rem;
        display: inline-block;
      }
    }
  }
.grid > .row > .col.addr-info {
    padding-right: 1em;
}
.grid > .row > .col.query-side {
    padding-left: 1em;
}
.page-layout {
  margin: 1.5rem auto;
  max-width: $fullWidth;
  border: 1px solid #666;
  box-shadow: 0 0 1.25rem 1px black;
  min-height: 320px;
  margin-bottom: 3rem;
  padding: 3rem 2rem;
}
ul.tick {
  list-style: none;
  & li {
    position: relative;
    margin-left: 1rem;
    &:before {
      display: inline-block;
      font-family: FontAwesome;
      font-style: normal;
      font-weight: normal;
      line-height: 1;
      -webkit-font-smoothing: antialiased;
      content: "\f046";
      position: absolute;
      left: -1.5rem;
    }
  }
}

.sample-testimonial {
  padding: 1em 2em;
}
.testimonial {
  background: #94C7E8;
  text-align: justify;
  position: relative;
  padding: 1em 2em;
  padding-left: 3em;
  &:before {
    content: "\201C";
    display: block;
    font-size: 4em;
    width: 2em;
    position: absolute;
    top: 1rem;
    left: 1rem;
    line-height: .75;
  }
  &.fa:before {
    content: "\f10d";
    font-family: FontAwesome;
  }
  & [itemprop="reviewer"] {
    text-align: right;
    font-style: italic;
    font-weight: 700;
  }
}

.dual-column-r {
  & > .grid.cnt2 {
    & > .row {
      & > .col:nth-child(2) {
        padding: 1.5rem 1.5rem 0 0;
      }
    }
  }
}
.dual-column-l {
  & > .grid.cnt2 {
    & > .row {
      & > .col:nth-child(2) {
      padding: 1.5rem 0 0 1.5rem;
      }
    }
  }
}

.grid.cnt3.highlight-mid .row .col:nth-child(2) {
  border-left: 1px solid #ccc;
	border-right: 1px solid #ccc;
	border-collapse: collapse;
}

}
.callout-home {
  & .row {
    & .col {
      text-align: center;
    }
  }
}
.bot-links-body {
  background: $txtColorLight;
  & nav.horizontal.nav-menu {
    text-align: center;
  }
}
.main-footer {
  min-height: 100px;
  color: $txtColorLight;
  background: $txtColor;
  padding: .25rem;
}


[itemType="http://schema.org/BlogPosting"] {
  & .grid.cnt4 {
    & .row {
      & > .sp3 {
        padding-left: 1.5rem;
      }
    }
  }
}
```
