### ISSUE TITLE
@extend directive wrong compilation with parent selector

### ISSUE THREAD

**Issue by atna** [leafo/scssphp#396]
In SASS:
```sass
%pagination-bullet {
	width: 6px;
	height: 6px;
	margin-left: 5px;
	&:first-child {
		margin-left: 0;
	}
	&.is-active {
		background-color: $color-base;
	}
}

.pagination {
    &-bullet {
       @extend %pagination-bullet;
    }
}
```
What it's compile:
```css
.pagination-bullet {
    width: 6px;
    height: 6px;
    margin-left: 5px;
}
-bullet.pagination:first-child {
    margin-left: 0;
}
-bullet.pagination.is-active  {
    background-color: #ccc;
}
```
And should be:
```css
.pagination-bullet:first-child {
    margin-left: 0;
}
.pagination-bullet.is-active {
    background-color: #ccc;
}
```
