### ISSUE TITLE
Undefined variable in Bootstrap 4 Alpha 6

### ISSUE THREAD

**Issue by piter2k1** [leafo/scssphp#492]
Problematic code:
```scss
body {
    @include media-breakpoint-between(md, lg) {
        padding: 8px 0;
    }
}
```
scssphp compiler output:
`Undefined variable $min: line: 61`

I tried resolve this issue.
This is `media-breakpoint-between` code with nested mixins. All of this mixins work properly when I use they separately.
```scss
@mixin media-breakpoint-between($lower, $upper, $breakpoints: $grid-breakpoints) {
  @include media-breakpoint-up($lower, $breakpoints) {
    @include media-breakpoint-down($upper, $breakpoints) {
      @content;
    }
  }
}
```

Variable **$min** is in `media-breakpoint-up` mixin:
```scss
@mixin media-breakpoint-up($name, $breakpoints: $grid-breakpoints) {
  $min: breakpoint-min($name, $breakpoints);
  @if $min {
    @media (min-width: $min) {
      @content;
    }
  } @else {
    @content;
  }
}
```

This works properly:
```scss
body {
    @include media-breakpoint-up(md) {
        padding: 8px 0;
    }
}
```
and
```scss
body {
    @include media-breakpoint-down(lg) {
        padding: 8px 0;
    }
}
```

I used 0.6.6 version of scssphp and latest from branch master.
