### ISSUE TITLE
@extend in pseudo selectors stops compiling

### ISSUE THREAD

**Issue by Twansparant** [leafo/scssphp#509]
The following markup won't compile to css, without any exception errors thrown:

```scss
$color-1: #000;
$color-2: #999;

.b-block {
  background: $color-1;

  &__element {
    background: $color-1;
    
    &:hover {
      background: $color-1;
    }

    &--modifier {
      background: $color-2;

      &:hover {
        @extend .b-block__element--modifier;
      }
    }
  }
}
```

**Expected results (matches SassMeister behavior):**
```css
.b-block {
  background: #000;
}
.b-block__element {
  background: #000;
}
.b-block__element:hover {
  background: #000;
}
.b-block__element--modifier, .b-block__element--modifier:hover {
  background: #999;
}
```

**Actual results using scssphp:**
None (no exception errors either)

**My code**:

```php
use Leafo\ScssPhp\Compiler;
try {
  // Compile scss to css
  $scss     = new Compiler();
  $scss->setFormatter('Leafo\ScssPhp\Formatter\Crunched');
  $style    = $scss->compile($value);

  return $style;

} catch (\Exception $e) {
  error_log($e);

  return false;
}
```

Commenting out this line:
```scss
@extend .b-block__element--modifier;
``` 
will return the expected result.

Any ideas what might be causing this?
Thanks!
