### ISSUE TITLE
pscss exhausts memory, is killed compiling nested a.class

### ISSUE THREAD

**Issue by gsmith-daed** [leafo/scssphp#522]
With this minimal SCSS, pscss 0.6.7 uses up all its process memory, and is killed:

```scss
a {
  color: #fff;
}

a:link {
  @extend a;
}

a:visited {
  @extend a;
}

a:active {
  @extend a;
}

a:hover {
  @extend a;
}

.nest a.some-class {
  color: #ccc;
}
```

Ruby sass compiles it successfully. Removing `.some-class` fixes it for pscss as well.
