### ISSUE TITLE
No function calls and ellipsis variable in call() arguments

### ISSUE THREAD

**Issue by gabor-udvari** [leafo/scssphp#569]
According to [the documentation](http://sass-lang.com/documentation/Sass/Script/Functions.html#call-instance_method) and Ruby Sass and Dart Sass functionality, all the below examples should give the same output:

```scss
.does-complie-1 {
  color: call(lighten, #000, 40%);
}

.does-compile-2 {
  $color: #000;
  $percent: 40%;
  color: call(lighten, $color, $percent);
}

.does-not-compile-1 {
  $args: (#000, 40%);
  color: call(lighten, nth($args, 1), nth($args, 2));
}

.does-not-compile-2 {
  $args: (#000, 40%);
  color: call(lighten, $args...);
}
```

But the last two sections do not compile and throw an error:
```
 [error]  expecting color: line 20 
```
