### ISSUE TITLE
Dot in string variable

### ISSUE THREAD

**Issue by chvilalukas** [leafo/scssphp#622]
If I have dynamics created variable $img = 'images/logo.png', created by PHP code:
```php
$this->scss->setVariables(array(
  'img' => 'images/logo.png'
));
```

And SCSS:
```css
.logo {
  background: url('#{$img}') no-repeat;
}
```

Compiler return these CSS (URL without file extension):
```css
.logo {
  background: url('images/logo') no-repeat;
}
```
