### ISSUE TITLE
How output md5 hash (first char is a digit) from value?

### ISSUE THREAD

**Issue by ange007** [leafo/scssphp#631]
Hello.
I tried output $id variables which may begin with a digit *(md5)*.
If so, the variable is broken up into several hashes.

**Source**
```scss
.shortcode-#{$id} {
```
```scss
$selector: '.shortcode-' + $id;
#{$selector} {
```

**Result**
![chrome_2019-02-26_17-37-40](https://user-images.githubusercontent.com/2736539/53425186-4047f200-39ed-11e9-9f10-76621a004310.png)

How to get rid of it?
