### ISSUE TITLE
nested strings not unquoted

### ISSUE THREAD

**Issue by mschaefer** [leafo/scssphp#65]
When compiling Foundation, we ran into a problem with their media query variables (example below). They use nested double quoted-strings to define $small. I don't see a need for the quotes around the interpolated $small-screen variable, but scssphp doesn't unquote the string, leading to a bad media directive in the final css.

Example:
```css
$small-screen: 48em !default;
$small: "only screen and (min-width:"#{$small-screen}")" !default;

@media #{$small} {
	div {
		display: none; } }
```
scssphp compiles to bad media directive:
```css
@media "only screen and (min-width:"48em")" {
  div {
    display: none; } }
```
We expect
 ```css
@media only screen and (min-width:48em) {
```

Thanks for your work!
