### ISSUE TITLE
Adding line numbers of original scss files to compiled css files for debugging

### ISSUE THREAD

**Issue by frankvanrest** [leafo/scssphp#88]
A great feature of CodeKit is that it puts line numbers of the scss-source files to the compiled css for debugging purposes. 

Example:

```css
/* line 1, ../scss/_reset.scss */
* {
  vertical-align: baseline;
  font-weight: inherit;
  font-family: inherit;
  font-style: inherit;
  font-size: 100%;
  border: 0 none;
  outline: 0;
  padding: 0;
  margin: 0; }
```

This makes finding the correct source from the css file a lot easier. Is there any way to add these line numbers to the generated css files?
