### ISSUE TITLE
Function arguments are lost inside of @content block

### ISSUE THREAD

**Issue by leafo** [leafo/scssphp#93]
Similar to #90 

``` scss
@mixin content_test {
    span {
        $color: green;
        @content;
    }
}



@function func_test($c) {
    @return $c + 1;
}

div {
    @include content_test {
        height: func_test(2px);
    }
}
```

outputs 1 instead of 3px
